services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection="Server=192.168.24.30,5432;Database=testdb;User Id=OPS;Password=mypassword;"