services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection="Server=localhost;Port=3306;Database=testdb;User=OPS;Password=mypassword;"
