version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection="Host=192.168.24.30;Port=5432;Database=testdb;Username=OPS;Password=mypassword;"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "OPS"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "testdb"
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
